# app/_config/routes.yml
---
Name: approutes
After: '#coreroutes'
---
SilverStripe\Control\Director:
  rules: 
    'api/venues': 'App\Control\VenueController'
    'api/images': 'App\Control\ImageController'
    'api/chips': 'App\Control\ChipController'